[package]
name = "ipc"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
net = { workspace = true }
paths = { workspace = true }

anyhow = { workspace = true }
futures = "0.3"
gpui = { workspace = true }
gpui_tokio = { workspace = true }
tokio = { workspace = true }
tarpc = { workspace = true }
tokio-serde = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true, features = ["log"] }
