[package]
name = "keyway"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "keyway"
path = "src/main.rs"

[dependencies]

#
# Workspace member crates
#

keyway_assets = { workspace = true }
keyway_i18n = { workspace = true }
keyway_ipc = { workspace = true }
keyway_core = { workspace = true }
keyway_ktracing = { workspace = true }
keyway_util = { workspace = true }
keyway_workspace = { workspace = true }

keyway_clipboard = { workspace = true }

#
# External crates
#

anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
gpui = { workspace = true }
gpui-component = { workspace = true }
gpui_platform = { workspace = true }
gpui_tokio = { workspace = true }
