[package]
name = "keyway"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "keyway"
path = "src/main.rs"

[dependencies]

#
# Workspace member crates
#

assets = { workspace = true }
i18n = { workspace = true }
ipc = { workspace = true}
runtime = { workspace = true }
ktracing = { workspace = true }
util = { workspace = true }
workspace = { workspace = true }

clipboard = { workspace = true }

#
# External crates
#

anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
gpui = { workspace = true }
gpui-component = { workspace = true }
gpui_platform = { workspace = true }
gpui_tokio = { workspace = true }
