[package]
name = "command"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
collections = { workspace = true }

gpui = { workspace = true }
inventory = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }