[package]
name = "keyway_workspace"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
keyway_core = { workspace = true }
keyway_ui = { workspace = true }

gpui = { workspace = true }
gpui-component = { workspace = true }
nucleo = { workspace = true }
tracing = { workspace = true }
